function Jobs() {
    const Vacancies :any= [
        {
            ref: 1,
            title: 'Frontend Developer',
            description: 'We are looking for a Frontend Developer to join our team.',
            branch: 'Eland',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        },
        {
            ref: 2,
            title: 'Backend Developer',
            description: 'We are looking for a Backend Developer to join our team.',
            branch: 'Bodysendal',
            salary: '£30,000',
            type: 'Full-time',
            date: '2020-01-01',
        }
    ];
    return ( 
        <section>
            <div>
                <div>
                    <h1 className="font-black ">Current Vacancies</h1>
                </div>
                <div>
                    {
                        Vacancies.map((vacancy :any, index: number) => {
                            return (
                                <div className="group  bg-white " key={index}>
                                    <div className="border-dotted border-1 border-gray-400 mb-2 shadow-md p-3">
                                        <h2 className="font-bold text-gray-600">{vacancy.title + " | " + vacancy.branch}</h2>
                                        <p className="text-gray-400 clamp">{vacancy.description}</p>
                                        <button className="hidden group-hover:block bg-blue-400 text-white px-4 rounded-md mt-1">View Job</button>
                                    </div>
                                </div>
                            )
                        })
                    }
                </div>
            </div>
        </section>
     );
}

export default Jobs;